# Generated by Django 2.2.4 on 2019-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True)),
                ('feed_up', models.BooleanField(null=True)),
                ('fetch_up', models.BooleanField(null=True)),
            ],
        ),
    ]
